kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master
  event:
    - push
    - cron
steps:
  - name: checkin
    image: selenium/standalone-chrome:latest
    environment:
      TZ: Asia/Shanghai
      CONFIG:
        from_secret: CONFIG
    commands:
      - sudo apt update
      - sudo apt install -y --no-install-recommends python3-pip
      - pip3 install -r requirements.txt --no-cache-dir
      - python3 XMUAutoCheckIn.py

node:
  name: xw1_docker